// frontend/src/views/Login.vue
<script setup lang="ts">
import { ref } from 'vue'
import { useRouter } from 'vue-router'
import { useAuthStore } from '../stores/auth'

const username = ref('')
const password = ref('')
const error = ref('')
const loading = ref(false)

const authStore = useAuthStore()
const router = useRouter()

const login = async () => {
  error.value = ''
  loading.value = true
  
  try {
    await authStore.login(username.value, password.value)
    router.push('/')
  } catch (e: any) {
    error.value = e.response?.data?.detail || 'Login failed'
  } finally {
    loading.value = false
  }
}
</script>

<template>
  <div class="login-container">
    <div class="login-card">
      <h1>MonitoCam</h1>
      <form @submit.prevent="login">
        <div class="form-group">
          <label for="username">Usuario</label>
          <input
            id="username"
            v-model="username"
            type="text"
            required
            autocomplete="username"
          />
        </div>
        <div class="form-group">
          <label for="password">Contrasena</label>
          <input
            id="password"
            v-model="password"
            type="password"
            required
            autocomplete="current-password"
          />
        </div>
        <div v-if="error" class="error">{{ error }}</div>
        <button type="submit" :disabled="loading">
          {{ loading ? 'Entrando...' : 'Entrar' }}
        </button>
      </form>
    </div>
  </div>
</template>

<style scoped>
.login-container {
  min-height: 100vh;
  display: flex;
  align-items: center;
  justify-content: center;
  background: linear-gradient(135deg, #1a1a2e 0%, #16213e 100%);
}

.login-card {
  background: white;
  padding: 2rem;
  border-radius: 8px;
  box-shadow: 0 4px 20px rgba(0, 0, 0, 0.2);
  width: 100%;
  max-width: 400px;
}

h1 {
  text-align: center;
  color: #1a1a2e;
  margin-bottom: 2rem;
}

.form-group {
  margin-bottom: 1rem;
}

label {
  display: block;
  margin-bottom: 0.5rem;
  color: #333;
}

input {
  width: 100%;
  padding: 0.75rem;
  border: 1px solid #ddd;
  border-radius: 4px;
  font-size: 1rem;
}

input:focus {
  outline: none;
  border-color: #1a1a2e;
}

button {
  width: 100%;
  padding: 0.75rem;
  background: #1a1a2e;
  color: white;
  border: none;
  border-radius: 4px;
  font-size: 1rem;
  cursor: pointer;
  margin-top: 1rem;
}

button:hover:not(:disabled) {
  background: #16213e;
}

button:disabled {
  opacity: 0.6;
  cursor: not-allowed;
}

.error {
  color: #e94560;
  margin-top: 1rem;
  text-align: center;
}
</style>

// frontend/src/app/features/auth/login.component.ts
import { Component, signal, inject } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { Router } from '@angular/router';
import { AuthService } from '../../core/auth.service';

@Component({
  selector: 'app-login',
  standalone: true,
  imports: [FormsModule],
  templateUrl: './login.component.html',
  styleUrl: './login.component.css'
})
export class LoginComponent {
  private authService = inject(AuthService);
  private router = inject(Router);

  username = '';
  password = '';
  loading = signal(false);
  error = signal('');

  async login(): Promise<void> {
    this.error.set('');
    this.loading.set(true);

    try {
      await this.authService.login(this.username, this.password);
      this.router.navigate(['/']);
    } catch (e: unknown) {
      const error = e as { error?: { detail?: string } };
      this.error.set(error.error?.detail || 'Login failed');
    } finally {
      this.loading.set(false);
    }
  }
}

<div class="login-container">
  <div class="login-card">
    <h1>MonitoCam</h1>
    <p class="login-subtitle">Sistema de Vigilancia</p>
    <form (ngSubmit)="login()">
      <div class="form-group">
        <label for="username">Usuario</label>
        <input
          id="username"
          [(ngModel)]="username"
          name="username"
          type="text"
          required
          autocomplete="username"
        />
      </div>
      <div class="form-group">
        <label for="password">Contrasena</label>
        <input
          id="password"
          [(ngModel)]="password"
          name="password"
          type="password"
          required
          autocomplete="current-password"
        />
      </div>
      @if (error()) {
        <div class="error">{{ error() }}</div>
      }
      <button type="submit" [disabled]="loading()">
        {{ loading() ? 'Entrando...' : 'Entrar' }}
      </button>
    </form>
  </div>
</div>
