// frontend/src/views/Recordings.vue
<script setup lang="ts">
import { ref, onMounted, onUnmounted } from 'vue'
import { recordingsApi, camerasApi, type Camera } from '../api/client'

const gifs = ref<any[]>([])
const cameras = ref<Camera[]>([])
const loading = ref(false)
const selectedCamera = ref<number | null>(null)
const selectedGif = ref<any>(null)
const autoRefresh = ref(true)
let refreshInterval: number | null = null



interface GifItem {
  id: string
  camera_id: number
  camera_name: string
  filename: string
  path: string
  timestamp: string
  size: number
}

const loadGifs = async () => {
  loading.value = true
  try {
    const params: any = {}
    if (selectedCamera.value) params.camera_id = selectedCamera.value
    const response = await recordingsApi.listGifs(params)
    gifs.value = response.data
  } catch (e) {
    console.error('Error loading gifs:', e)
  } finally {
    loading.value = false
  }
}

const deleteGif = async (gif: GifItem, event: Event) => {
  event.stopPropagation()
  if (!confirm(`Eliminar grabación ${gif.filename}?`)) return
  try {
    await recordingsApi.delete(gif.id)
    await loadGifs()
  } catch (e) {
    console.error('Error deleting:', e)
  }
}

const loadCameras = async () => {
  try {
    const response = await camerasApi.list()
    cameras.value = response.data
  } catch (e) {
    console.error('Error loading cameras:', e)
  }
}

const formatSize = (bytes: number) => {
  if (!bytes) return '0 B'
  const units = ['B', 'KB', 'MB']
  let i = 0
  while (bytes >= 1024 && i < units.length - 1) {
    bytes /= 1024
    i++
  }
  return `${bytes.toFixed(1)} ${units[i]}`
}

const formatTimestamp = (ts: string) => {
  if (!ts) return ''
  const parts = ts.split('_')
  if (parts.length >= 2) {
    const date = parts[parts.length - 2]
    const time = parts[parts.length - 1].replace('-', ':')
    return `${date} ${time}`
  }
  return ts.replace(/_/g, ' ')
}


const openVideo = (gif: GifItem) => {
  selectedGif.value = gif
}

const closeVideo = () => {
  selectedGif.value = null
}

const toggleAutoRefresh = () => {
  autoRefresh.value = !autoRefresh.value
  if (autoRefresh.value) {
    startAutoRefresh()
  } else {
    stopAutoRefresh()
  }
}

const startAutoRefresh = () => {
  if (refreshInterval) return
  refreshInterval = window.setInterval(loadGifs, 10000)
}

const stopAutoRefresh = () => {
  if (refreshInterval) {
    clearInterval(refreshInterval)
    refreshInterval = null
  }
}

onMounted(() => {
  loadCameras()
  loadGifs()
  startAutoRefresh()
})

onUnmounted(() => {
  stopAutoRefresh()
})
</script>

<template>
  <div class="recordings-page">
    <div class="header">
      <h1>Grabaciones</h1>
      <div class="header-actions">
        <button @click="loadGifs" class="btn-refresh">
          Actualizar
        </button>
        <button @click="toggleAutoRefresh" :class="['btn-auto', { active: autoRefresh }]">
          {{ autoRefresh ? 'Auto ON' : 'Auto OFF' }}
        </button>
      </div>
    </div>

    <div class="filters">
      <div class="filter-group">
        <label>Camara</label>
        <select v-model="selectedCamera" @change="loadGifs">
          <option :value="null">Todas</option>
          <option v-for="cam in cameras" :key="cam.id" :value="cam.id">
            {{ cam.name }}
          </option>
        </select>
      </div>
      <div class="filter-group">
        <span class="count">{{ gifs.length }} grabaciones</span>
      </div>
    </div>

    <div v-if="loading && gifs.length === 0" class="loading">
      Cargando...
    </div>

    <div v-if="selectedGif" class="modal" @click.self="closeVideo">
      <div class="modal-content video-modal">
        <div class="modal-header">
          <div class="modal-info">
            <h2>{{ selectedGif.camera_name }}</h2>
            <span class="timestamp">{{ formatTimestamp(selectedGif.timestamp) }}</span>
          </div>
          <button @click="closeVideo" class="close-btn">X</button>
        </div>
        <video 
          :src="`/api/recordings/${selectedGif.id}/download`" 
          controls 
          autoplay
        >
          Tu navegador no soporta video.
        </video>
        <div class="modal-footer">
          <a :href="`/api/recordings/${selectedGif.id}/download`" class="btn-download" download>
            Descargar MP4
          </a>
        </div>
      </div>
    </div>

    <div v-if="!loading && gifs.length === 0" class="empty">
      No hay grabaciones
    </div>

    <div v-else class="gifs-grid">
      <div 
        v-for="gif in gifs" 
        :key="gif.id" 
        class="gif-card"
        @click="openVideo(gif)"
      >
        <div class="gif-preview">
          <img 
            :src="`/api/recordings/gifs/${gif.id}/file`" 
            :alt="gif.filename"
            loading="lazy"
          />
          <div class="gif-overlay">
            <span class="play-icon">▶</span>
          </div>
        </div>
        <div class="gif-info">
          <h3>{{ gif.camera_name }}</h3>
          <p class="timestamp">{{ formatTimestamp(gif.timestamp) }}</p>
          <div class="gif-footer">
            <p class="size">{{ formatSize(gif.size) }}</p>
            <button class="btn-delete" @click="deleteGif(gif, $event)" title="Eliminar">
              X
            </button>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<style scoped>
.recordings-page {
  padding: 0;
}

.header {
  display: flex;
  justify-content: space-between;
  align-items: center;
  margin-bottom: 1.5rem;
}

h1 {
  color: #1a1a2e;
  margin: 0;
}

.header-actions {
  display: flex;
  gap: 0.5rem;
}

.btn-refresh {
  background: #4caf50;
}

.btn-refresh:hover {
  background: #45a049;
}

.btn-auto {
  background: #666;
}

.btn-auto.active {
  background: #4caf50;
}

.filters {
  display: flex;
  gap: 1rem;
  align-items: center;
  margin-bottom: 1.5rem;
  flex-wrap: wrap;
}

.filter-group {
  display: flex;
  flex-direction: column;
  gap: 0.25rem;
}

.filter-group label {
  font-size: 0.75rem;
  color: #666;
}

.filter-group select {
  padding: 0.5rem;
  border: 1px solid #ddd;
  border-radius: 4px;
  min-width: 150px;
}

.count {
  color: #888;
  font-size: 0.85rem;
}

button {
  background: #1a1a2e;
  color: white;
  border: none;
  padding: 0.5rem 1rem;
  border-radius: 4px;
  cursor: pointer;
  font-size: 0.85rem;
}

button:hover {
  background: #16213e;
}

.loading, .empty {
  text-align: center;
  color: #666;
  padding: 3rem;
}

.modal {
  position: fixed;
  top: 0;
  left: 0;
  right: 0;
  bottom: 0;
  background: rgba(0, 0, 0, 0.85);
  display: flex;
  align-items: center;
  justify-content: center;
  z-index: 100;
}

.video-modal {
  background: #1a1a2e;
  border-radius: 8px;
  width: 90%;
  max-width: 900px;
  overflow: hidden;
}

.modal-header {
  display: flex;
  justify-content: space-between;
  align-items: center;
  padding: 1rem;
  background: #16213e;
}

.modal-info h2 {
  color: white;
  margin: 0;
  font-size: 1rem;
}

.modal-info .timestamp {
  color: #888;
  font-size: 0.85rem;
}

.close-btn {
  background: transparent;
  border: 1px solid white;
  padding: 0.25rem 0.75rem;
}

video {
  width: 100%;
  max-height: 70vh;
  display: block;
  background: #000;
}

.modal-footer {
  padding: 1rem;
  background: #16213e;
}

.btn-download {
  display: inline-block;
  background: #4caf50;
  color: white;
  padding: 0.5rem 1rem;
  border-radius: 4px;
  text-decoration: none;
  font-size: 0.85rem;
}

.btn-download:hover {
  background: #45a049;
}

.gifs-grid {
  display: grid;
  grid-template-columns: repeat(auto-fill, minmax(400px, 1fr));
  gap: 1rem;
}

.gif-card {
  background: white;
  border-radius: 8px;
  overflow: hidden;
  box-shadow: 0 2px 8px rgba(0, 0, 0, 0.1);
  cursor: pointer;
  transition: transform 0.2s, box-shadow 0.2s;
}

.gif-card:hover {
  transform: translateY(-2px);
  box-shadow: 0 4px 12px rgba(0, 0, 0, 0.15);
}

.gif-preview {
  position: relative;
  aspect-ratio: 16/9;
  background: #000;
  overflow: hidden;
}

.gif-preview img {
  width: 100%;
  height: 100%;
  object-fit: cover;
}

.gif-overlay {
  position: absolute;
  top: 0;
  left: 0;
  right: 0;
  bottom: 0;
  background: rgba(0, 0, 0, 0.3);
  display: flex;
  align-items: center;
  justify-content: center;
  opacity: 0;
  transition: opacity 0.2s;
}

.gif-card:hover .gif-overlay {
  opacity: 1;
}

.play-icon {
  font-size: 2rem;
  color: white;
  text-shadow: 0 2px 4px rgba(0, 0, 0, 0.3);
}

.gif-info {
  padding: 0.75rem;
}

.gif-info h3 {
  margin: 0 0 0.25rem 0;
  color: #1a1a2e;
  font-size: 0.9rem;
}

.gif-info .timestamp {
  color: #333;
  font-size: 0.8rem;
  font-weight: 500;
  margin-bottom: 0.25rem;
}

.gif-info .size {
  color: #888;
  font-size: 0.75rem;
  margin: 0;
}

.gif-footer {
  display: flex;
  justify-content: space-between;
  align-items: center;
  margin-top: 0.25rem;
}

.btn-delete {
  background: #e94560;
  color: white;
  border: none;
  width: 22px;
  height: 22px;
  border-radius: 4px;
  cursor: pointer;
  font-size: 0.75rem;
  display: flex;
  align-items: center;
  justify-content: center;
  padding: 0;
  line-height: 1;
}

.btn-delete:hover {
  background: #d63650;
}
</style>

// frontend/src/app/features/recordings/recordings.component.ts
import { Component, OnInit, OnDestroy, signal, inject } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { ApiService } from '../../services/api.service';
import { Camera } from '../../models/camera.model';
import { GifItem } from '../../models/recording.model';

@Component({
  selector: 'app-recordings',
  standalone: true,
  imports: [FormsModule],
  templateUrl: './recordings.component.html',
  styleUrl: './recordings.component.css'
})
export class RecordingsComponent implements OnInit, OnDestroy {
  private api = inject(ApiService);

  gifs = signal<GifItem[]>([]);
  cameras = signal<Camera[]>([]);
  loading = signal(false);
  selectedCamera: number | null = null;
  selectedGif = signal<GifItem | null>(null);
  autoRefresh = signal(true);
  private refreshInterval: ReturnType<typeof setInterval> | null = null;

  ngOnInit(): void {
    this.loadCameras();
    this.loadGifs();
    this.startAutoRefresh();
  }

  ngOnDestroy(): void {
    this.stopAutoRefresh();
  }

  loadGifs(): void {
    this.loading.set(true);
    const params = this.selectedCamera ? { camera_id: this.selectedCamera } : undefined;
    this.api.getGifs(params)
      .then(data => {
        this.gifs.set(data);
        this.loading.set(false);
      })
      .catch(() => this.loading.set(false));
  }

  loadCameras(): void {
    this.api.getCameras()
      .then(data => this.cameras.set(data));
  }

  deleteGif(gif: GifItem, event: Event): void {
    event.stopPropagation();
    if (!confirm(`Eliminar grabación ${gif.filename}?`)) return;
    this.api.deleteRecording(gif.id)
      .then(() => this.loadGifs());
  }

  cleanupOldRecordings(): void {
    const days = prompt('Eliminar grabaciones de hace cuántos días?', '7');
    if (!days) return;
    const daysNum = parseInt(days, 10);
    if (isNaN(daysNum) || daysNum < 0) {
      alert('Por favor ingresa un número válido de días');
      return;
    }
    if (!confirm(`Eliminar todas las grabaciones de hace más de ${daysNum} días?`)) return;
    this.api.cleanupOldRecordings(daysNum)
      .then(() => this.loadGifs())
      .catch(err => alert('Error al limpiar grabaciones: ' + err.message));
  }

  formatSize(bytes: number): string {
    if (!bytes) return '0 B';
    const units = ['B', 'KB', 'MB'];
    let i = 0;
    while (bytes >= 1024 && i < units.length - 1) {
      bytes /= 1024;
      i++;
    }
    return `${bytes.toFixed(1)} ${units[i]}`;
  }

  formatTimestamp(ts: string): string {
    if (!ts) return '';
    const parts = ts.split('_');
    if (parts.length >= 2) {
      const date = parts[parts.length - 2];
      const time = parts[parts.length - 1].replace('-', ':');
      return `${date} ${time}`;
    }
    return ts.replace(/_/g, ' ');
  }

  getGifUrl(id: string): string {
    return this.api.getGifUrl(id);
  }

  getDownloadUrl(id: string): string {
    return this.api.getDownloadUrl(id);
  }

  openVideo(gif: GifItem): void {
    this.selectedGif.set(gif);
  }

  closeVideo(): void {
    this.selectedGif.set(null);
  }

  toggleAutoRefresh(): void {
    this.autoRefresh.set(!this.autoRefresh());
    if (this.autoRefresh()) {
      this.startAutoRefresh();
    } else {
      this.stopAutoRefresh();
    }
  }

  startAutoRefresh(): void {
    if (this.refreshInterval) return;
    this.refreshInterval = setInterval(() => this.loadGifs(), 10000);
  }

  stopAutoRefresh(): void {
    if (this.refreshInterval) {
      clearInterval(this.refreshInterval);
      this.refreshInterval = null;
    }
  }
}

<div class="recordings-page">
  <div class="header">
    <h1>Recordings</h1>
    <div class="header-actions">
      <button (click)="cleanupOldRecordings()" class="btn-cleanup">Clean up</button>
      <button (click)="loadGifs()" class="btn-refresh">Refresh</button>
    </div>
  </div>

  <div class="filters">
    <div class="filter-group">
      <label>Camera</label>
      <select [ngModel]="selectedCamera()" (ngModelChange)="onCameraChange($event)">
        <option [ngValue]="null">All</option>
        @for (cam of cameras(); track cam.id) {
          <option [ngValue]="cam.id">{{ cam.name }}</option>
        }
      </select>
    </div>
    <div class="filter-group">
      <span class="count">{{ totalCount() }} recordings</span>
    </div>
  </div>

  @if (loading() && gifs().length === 0) {
    <div class="skeleton-grid">
      @for (_ of [].constructor(pageSize); track $index) {
        <div class="skeleton-card">
          <div class="skeleton-preview"></div>
          <div class="skeleton-info">
            <div class="skeleton-line"></div>
            <div class="skeleton-line short"></div>
            <div class="skeleton-line"></div>
          </div>
        </div>
      }
    </div>
  }

  @if (selectedGif()) {
    <div class="modal" (click)="closeVideo()">
      <div class="modal-content video-modal" (click)="$event.stopPropagation()">
        <div class="modal-header">
          <div class="modal-info">
            <h2>{{ selectedGif()!.camera_name }}</h2>
            <span class="timestamp">{{ formatTimestamp(selectedGif()!.timestamp) }}</span>
          </div>
          <button (click)="closeVideo()" class="close-btn">X</button>
        </div>
        <video [src]="getDownloadUrl(selectedGif()!.id)" controls autoplay>
          Tu navegador no soporta video.
        </video>
        <div class="modal-footer">
          <a [href]="getDownloadUrl(selectedGif()!.id)" class="btn-download" download>
            Download
          </a>
        </div>
      </div>
    </div>
  }

  @if (!loading() && gifs().length === 0) {
    <div class="empty">No recordings found</div>
  }

  @if (selectedCamera(); as camId) {
    <div class="live-view-section">
      <app-live-view
        [cameraId]="camId"
      />
    </div>
  }

  @if (gifs().length > 0) {
    <div class="pagination">
      <button class="btn-pagination" (click)="prevPage()" [disabled]="currentPage() <= 1">
        « Anterior
      </button>
      <span class="page-info">Página {{ currentPage() }} de {{ totalPages() }}</span>
      <button class="btn-pagination" (click)="nextPage()" [disabled]="currentPage() >= totalPages()">
        Siguiente »
      </button>
    </div>
    <div class="gifs-grid">
      @for (gif of gifs(); track gif.id) {
        <div class="gif-card" (click)="openVideo(gif)">
          <div class="gif-preview">
            <img [src]="getGifUrl(gif.id)" [alt]="gif.filename" loading="lazy" />
            <div class="gif-scanlines"></div>
            <div class="gif-overlay">
              <span class="play-icon">▶</span>
            </div>
          </div>
          <div class="gif-info">
            <h3>{{ gif.camera_name }}</h3>
            <p class="timestamp">{{ formatTimestamp(gif.timestamp) }}</p>
            <div class="gif-footer">
              <p class="size">{{ formatSize(gif.size) }}</p>
              <button class="btn-delete" (click)="deleteGif(gif, $event)" title="Eliminar">X</button>
            </div>
          </div>
        </div>
      }
    </div>
  }
</div>
